addon/helpers/ember-basic-dropdown-hash.js
addon/templates/components/ember-basic-dropdown.hbs
app/helpers/ember-basic-dropdown-hash.js
package.json

Since this hash is going to be there in 2.3, lets use the polyfill

Use ember-hash-helper-polyfill

---

addon/components/basic-dropdown.js

Use getBoundingClientRect to get subpixel precission and also be more
efficient that with jquery's `offset` method

More efficient and accurate calculations

---

addon/components/basic-dropdown.js
package.json

I've been fixing a few of our addons and this was another getOwner update :)
If you pull this in, when do you think a beta release of power-select could ship (to include this) ?

[DEPENDENCY]: using getOwner to support ember 2.3

---

addon/components/basic-dropdown.js
tests/.jshintrc
tests/acceptance/opening-closing-order-test.js
tests/dummy/app/controllers/opening-closing-order.js
tests/dummy/app/router.js
tests/dummy/app/templates/opening-closing-order.hbs
tests/helpers/native-click.js
tests/helpers/native-focus.js
tests/helpers/start-app.js

The opened dropdown has to be closed before the new one opens.

Ensure the old dropdown is closed before the new one is opened

---

addon/components/basic-dropdown.js
app/styles/ember-basic-dropdown.scss

Decide if dropdown should be anchored to the left or the right based on available space

Add horizontal positioning for renderInPlace

---

addon/components/basic-dropdown.js

This is a first step into allowing dropdowns to coexist simultaneously,
to allow animations.

Use the dropdown's id for query the document, instead the class.

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

cibernox/ember-basic-dropdown#67

67 add aria label to trigger

---

addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
addon/templates/components/basic-dropdown/content.hbs
tests/dummy/app/templates/index.hbs

Less run-loops, less requestAnimationFrame, more Ember.

Simplified animation logic.

---

addon/components/basic-dropdown.js
tests/dummy/app/controllers/opening-closing-order.js

Maybe it’s also more performant since all reads and writes are together

Simplify position madness.

---

addon/components/basic-dropdown/content.js

Tapping should close the dropdown on touch-devices. closes #80

---

addon/components/basic-dropdown.js
tests/dummy/app/styles/app.scss
tests/dummy/app/templates/index.hbs
tests/integration/components/basic-dropdown-test.js

For now it works only if the dropdown is not rendered in place

Added new horizontalPosition="center" strategy.

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
addon/templates/components/basic-dropdown.hbs
addon/templates/components/basic-dropdown/content.hbs
bower.json
tests/integration/components/basic-dropdown/content-test.js
tests/integration/components/basic-dropdown/trigger-test.js

In tagless components it is null now

Stop relying in this.elementId

---

addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
addon/utils/computed-fallback-if-undefined.js
tests/dummy/app/components/my-custom-content.js
tests/dummy/app/components/my-custom-trigger.js
tests/dummy/app/templates/components/my-custom-content.hbs
tests/dummy/app/templates/components/my-custom-trigger.hbs
tests/integration/components/basic-dropdown-test.js

Allow to customize the inner components from the outside

---

CHANGELOG.md
addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

[BUGFIX] `renderInPlace` attempts to register a view with id null

---

addon/components/basic-dropdown/content.js

fixes https://github.com/cibernox/ember-basic-dropdown/issues/130

Fix issue where this.dropdownElement is undefined on IE 10

---

addon/components/basic-dropdown.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs
tests/integration/components/basic-dropdown-test.js

I think that at the end, schedule calling this action is bad.

Update in glimmer.

---

.gitignore
CHANGELOG.md
addon/components/basic-dropdown/trigger.js
tests/integration/components/basic-dropdown/trigger-test.js

[ENHANCEMENT] Bind `title` attribute in trigger component

---

addon/components/basic-dropdown.js
tests/dummy/app/templates/index.hbs

Fix `horizontalPosition=center`

---

addon/components/basic-dropdown/content.js
package.json

Stop using `ember-get-config` at all

Update ember-get-config again

---

addon/utils/calculate-position.js

Thanks for ember-basic-dropdown and ember-power-select!
There are some positioning issues, which makes the dropdown unusable, when the viewport is horizontally scrolled. Not scrolled:
Scrolled:
This PR fixes that and some more positioning issues. This is what I changed:
- Added support for when the page is horizontally scrolled. The function wasn't taking
`scroll.left` into account, which causes the dropdown to drift to the
left as you scroll right.
- Improved horizontalPosition=auto to work better for dropdowns that are
smaller than their trigger element. It now considers which position
will show the most horizontal pixels of the dropdown in either left- or
right-aligned mode and updates the position accordingly.
- Made sure that `style.left` is set to `null` when `style.right` gets
set. …

Fixed issues in calculate-position.js (support for horizontal scrolling primarily)

---

.gitignore
config/deploy.js
package.json

It's not pretty, but it's something

Deploy dummy app as a demo to showcase the component

---

addon/components/basic-dropdown/trigger.js

Which opens and immediatly closes the component

Not preventing default caused both touchend and click handlers to be fired

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/utils/calculate-position.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs
tests/integration/components/basic-dropdown-test.js
tests/integration/components/basic-dropdown/content-test.js

This is almost working, and it wasn't that hard /cc @saladfork

Allow `verticalPosition="above"` when `renderInPlace=true`

---

README.md

Update README with body height info (closes #196)

---

index.js

Use es6 syntax

---

tests/dummy/app/templates/public-pages/cookbook/index.hbs

Fix typo in 'public-pages/cookbook/index.hbs'

---

app/styles/ember-basic-dropdown.less
index.js

Prerequisite for https://github.com/cibernox/ember-power-select/pull/783

Add Less support

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
tests/dummy/app/templates/legacy-demo.hbs
tests/integration/components/basic-dropdown/trigger-test.js

This is needed to allow labels to focus the trigger

[ENHANCEMENT] Allow to customise trigger’s id

---

CHANGELOG.md
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
tests/integration/components/basic-dropdown-test.js
tests/integration/components/basic-dropdown/trigger-test.js

Use `aria-owns` instead of `aria-controls` to link trigger and dropdown

---

CHANGELOG.md
addon/components/basic-dropdown/trigger.js
tests/integration/components/basic-dropdown/trigger-test.js

Remove aria-haspopup by default (but can be bound if passed in)

---

addon/components/basic-dropdown/content-element.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown/content.hbs
app/components/basic-dropdown/content-element.js
tests/integration/components/basic-dropdown/content-test.js

This allows customization of the tagName.
I tried to make it as less intrusive as possible.

add the possibility to customize the content element tagName

---

tests/dummy/app/templates/public-pages/docs/custom-position.hbs

I found these while I was using calculatePosition.

Fix documentation typos

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/utils/calculate-position.js
tests/dummy/app/templates/public-pages/docs/api-reference.hbs
tests/dummy/app/templates/public-pages/docs/custom-position.hbs
tests/integration/components/basic-dropdown-test.js

Unify `calculatePosition` and `calculateInPlacePosition`

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

Followed the same path as `width`.

allow calculatePosition to return custom height

---

package.json
tests/integration/components/basic-dropdown-test.js
tests/integration/components/basic-dropdown/content-test.js
yarn.lock

Leverage ember-native-dom-helpers

---

addon/templates/components/basic-dropdown/content.hbs
app/styles/ember-basic-dropdown.scss
yarn.lock

Fixed linebreak when trigger is inlined

---

yarn.lock

Fixes issue with babel-plugin-htmlbars-inline-precompile.
Closes #247.

Update to latest deps.

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
addon/utils/calculate-position.js
tests/dummy/app/styles/_base.scss
tests/dummy/app/styles/demos/scrollable-container.scss
tests/dummy/app/templates/scrolling-container.hbs
tests/dummy/app/templates/snippets/scrollable-container-1.hbs
yarn.lock

@RustyToms I think I've squared the circle finally. 
This approach in your demo seems to work automatically, without forcing the user to pass **any** option. Not even `destinatination`. I did it by automatically find all the parents with scroll and reposition when any of them scrolls.
Can you give it a try?

Attempt automatic nested scroll detection (N levels)

---

README.md

to match
https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/utils/calculate-position.js#L107

[Docs]: Update README to match API

---

addon/components/basic-dropdown/content.js
tests/dummy/app/templates/legacy-demo.hbs
tests/integration/components/basic-dropdown-test.js

Resolves https://github.com/cibernox/ember-basic-dropdown/issues/286

Infinite nesting

---

addon/utils/calculate-position.js

I believe this should fix #290

Pass along missing parameter which result in options being missed

---

addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
tests/dummy/app/styles/_layout.scss
tests/dummy/app/templates/legacy-demo.hbs

Add events to the document, not the body

---

addon/components/basic-dropdown.js
addon/utils/calculate-position.js
tests/dummy/app/templates/legacy-demo.hbs
tests/dummy/app/templates/public-pages/docs/position.hbs
tests/dummy/app/templates/snippets/position-1.hbs
tests/integration/components/basic-dropdown-test.js

Closes #312
It turns out it wasn't that hard!

Add "auto-right" strategy for horizontal positioning

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content-element.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
addon/utils/computed-fallback-if-undefined.js
package.json
test-support/helpers/ember-basic-dropdown.js
tests/dummy/app/components/autofocus-input.js
tests/dummy/app/components/my-custom-content.js
tests/dummy/app/components/my-custom-trigger.js
tests/dummy/app/controllers/public-pages.js
tests/dummy/app/controllers/public-pages/docs.js
tests/dummy/app/controllers/public-pages/docs/content-events.js
tests/dummy/app/controllers/public-pages/docs/custom-position.js
tests/dummy/app/controllers/public-pages/docs/dropdown-events.js
tests/dummy/app/controllers/public-pages/docs/position.js
tests/dummy/app/controllers/public-pages/docs/trigger-events.js
tests/dummy/app/templates/snippets/content-events-1-js.js
tests/dummy/app/templates/snippets/custom-position-1-js.js
tests/dummy/app/templates/snippets/custom-position-2-js.js
tests/dummy/app/templates/snippets/dropdown-events-2-js.js
tests/dummy/app/templates/snippets/position-1-js.js
tests/dummy/app/templates/snippets/trigger-events-1-js.js
tests/dummy/app/templates/snippets/trigger-events-2-js.js
tests/dummy/app/templates/snippets/trigger-events-3-js.js
tests/dummy/app/templates/snippets/trigger-events-4-js.js
tests/integration/components/basic-dropdown/content-test.js
tests/integration/components/basic-dropdown/trigger-test.js
yarn.lock

Use new import paths thanks to ember-cli-babel 6.5.0

---

CHANGELOG.md
addon/components/basic-dropdown/trigger.js
tests/dummy/app/templates/legacy-demo.hbs
tests/dummy/app/templates/public-pages/docs/trigger-events.hbs
tests/dummy/app/templates/snippets/trigger-events-0.hbs
tests/integration/components/basic-dropdown-test.js
tests/integration/components/basic-dropdown/trigger-test.js

Allow to open the dropdown with clicks instead of mousedown

---

CHANGELOG.md
addon/utils/calculate-position.js
package.json
tests/dummy/app/templates/legacy-demo.hbs
tests/integration/components/basic-dropdown-test.js
yarn.lock

Before this change they had either `--above` or nothing. This class was commonly used by 
animations.
Closes #300 (hopefully)

Dropdowns rendered `inPlace` must have the `--below` class when rendered below

---

addon/components/basic-dropdown/trigger.js
tests/integration/components/basic-dropdown/trigger-test.js

This will make it possible for parent components to pass in a value for
this and they won't have to worry about it breaking if the value is not
defined

Have basic-dropdown trigger aria-role default to 'button'

---

addon/utils/calculate-position.js
tests/integration/components/basic-dropdown-test.js

Position calculation for `right` and `auto-right` when renderInPlace=true 

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
addon/utils/calculate-position.js

I removed all the  `self.document` and `self.window` occurrences from the addon

Self.document and self.window are undefined in some cases

---

README.md

In order to create an Ember Twiddle, it's necessary to manually add a `div` for `ember-whormhole`.
Thanks to cibernox for teaching me that 👍

Update information about Ember-Twiddle

---

addon/components/basic-dropdown.js

Fix set issue #431

---

app/utils/calculate-position.js

export calculate-position as public api

---

tests/unit/utils/calculate-position-test.js

Refs #478  and #479 
I took a stab at it. Not sure how to qualify it as 'public' API.
sorry, don't have much experience with tests.

added test for existance of calculate position

---

addon/components/basic-dropdown-content.js

Use `set` instead of direct assignment.

---

addon/components/basic-dropdown.js

This PR fixes assertion throwing on exception when rendering dropdown menu in place.

Fix development assertion when not rendering in place

---

addon/components/basic-dropdown.js

Use set when changing `previousVerticalPosition` and `previousHorizontalPosition`.

---

addon/components/basic-dropdown-content.ts

ignore comment node changes on mutation observer

---

addon/components/basic-dropdown-content.js
tests/integration/components/content-test.js

@shouldReposition function can be used to control which mutations should trigger a reposition

@shouldReposition function

---

addon/components/basic-dropdown-content.ts
tests/dummy/app/templates/public-pages/docs/api-reference.hbs
tests/integration/components/content-test.js

@shouldReposition can be used to avoid unnecessary repositions

---

addon/components/basic-dropdown.ts

fix otherStyles changes

---

addon/components/basic-dropdown-content.js

Related https://github.com/cibernox/ember-basic-dropdown/pull/541

correctly compare against undefined

---

addon/components/basic-dropdown.ts

Closes https://github.com/cibernox/ember-basic-dropdown/issues/574

Use assign polyfill from Ember instead Object.assign for IE11

---

addon/components/basic-dropdown.ts

Array.includes -> Array.indexOf for IE11

---

addon/components/basic-dropdown-content.ts
addon/components/basic-dropdown-trigger.ts
addon/utils/has-moved.ts
tests/integration/components/content-test.js
tests/integration/components/trigger-test.js

Related to: https://github.com/cibernox/ember-power-select/issues/1387
See also: https://github.com/cibernox/ember-power-select/pull/1406

Add support for stylus (Apple Pencil)

---

addon/components/basic-dropdown-content.ts
tests/integration/components/content-test.js

Fixes #527: Erratic dropdown positioning

---

addon/templates/components/basic-dropdown.hbs

- Fixes build time deprecation warning

with -> let

---

package-lock.json
package.json

[ember-element-helper 0.6.0](https://github.com/tildeio/ember-element-helper/blob/main/CHANGELOG.md#v060-2022-02-05) has been released, unlocking embroider v1

upgrade to ember-element-helper@^0.6.0

---

tests/dummy/app/templates/public-pages/docs/api-reference.hbs

docs: add missing htmlTag attribute

---

addon/components/basic-dropdown-content.hbs
addon/components/basic-dropdown-content.ts
tests/integration/components/basic-dropdown-test.js

Fixes https://github.com/cibernox/ember-basic-dropdown/issues/707

Reset Styles Properly On Reposition

---

package-lock.json
package.json

Update ember-element-helper to v0.8.2

---

docs/app/templates/public-pages/docs/api-reference.hbs

DOCS: Fix typos

---

ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
ember-basic-dropdown/src/components/basic-dropdown.ts

Fix fastboot `ReferenceError: document is not defined`

---

docs/.eslintrc.js
docs/app/components/snippets/content-events-1.js
docs/app/controllers/public-pages/docs/content-events.js
docs/package.json
ember-basic-dropdown/.eslintrc.cjs
ember-basic-dropdown/package.json
ember-basic-dropdown/src/components/basic-dropdown-content.ts
ember-basic-dropdown/src/components/basic-dropdown.ts
pnpm-lock.yaml
test-app/.eslintrc.js
test-app/package.json
test-app/tests/integration/components/basic-dropdown-test.js
test-app/tests/integration/components/content-test.js

Remove all using from `@ember/runloop` with `ember-lifeline`
See: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-runloop.md

Replace `@ember/runloop` with `ember-lifeline`

---

ember-basic-dropdown/src/modifiers/basic-dropdown-trigger.ts

silence chrome warning for non-passive 'touchstart' event.

---

ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
test-app/tests/integration/components/basic-dropdown-wormhole-test.js

Remove test-specific behaviour for BasicDropdownWormhole

---

ember-basic-dropdown/src/components/basic-dropdown.ts

… over root element as destination in tests
Close #943

Test: Prefer `config.destination` and default `ember-basic-dropdown-wormhole`
