cibernox/ember-basic-dropdown

addon/components/ember-basic-dropdown.js
addon/templates/components/ember-basic-dropdown.hbs
bower.json
package.json
tests/integration/components/ember-basic-dropdown-test.js

If the event sent to the outside gets defaultPrevented the default
behavior (toggle on enter, close on escape) won't execute.

Allow to send keydown events to the outside.

---

addon/components/basic-dropdown.js
app/styles/ember-basic-dropdown.scss

It turn out that the issues was not related with the boxing model or the border,
it was related with pixel rounding. `offsetWidth` returns rounded pixels, which
in standard displays is ok but in retina ones might make a 1px difference.

Use getBoundingClientRect instead of outerWidth

---

addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

Passing `tabindex=123` overrides the default tabindex, but when used in conjuntion
with `disabled=true` the latter still wins and the tabindex is -1.

Allow to override tabindex

---

addon/components/basic-dropdown.js

Since this component is very generic, it's styles have to also been very generic,
and therefore classes like `.disabled`, `.opened`, ect... should be avoided.
I've taken the BEM approach in this case, addind `--modifier` to the default class.
This is a breaking change that will cause a intermediate version bump.

Avoid overly generic css classes.

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

Now the yielded object has this form:
```js
{
isOpened: <boolean>,
actions: {
open: fn<evt>,
close: fn<evt>,
toggle: fn<evt>
}
}
```

Refactor yielded API

---

addon/components/basic-dropdown.js
tests/dummy/app/controllers/application.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs
tests/integration/components/basic-dropdown-test.js

This finally allows to pass the component a property to remotely control the component. 
When the property passes from falsey to truthy the component opens, and when goes to falsey it closes.
It is absolutely equivalent to open/close the component manually (the onOpen/onClose actions are invoked if provided), but at least for render the component already opened it avoids a repaint (render it closed and then re-render it opened)

Allowing to open close component passing `opened=true/false`

---

addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs

After some thought, this implementation seemed more efficient to me,
since it only does work when the received attribute is the `opened`
one, and the `publicAPI` is a computed property, meaning that is initialized
lazily and the all functions are reused.

Refactor open/close into CP instead of didReceiveAttrs

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

This should avoid the users to accidentally select text if they move the finger before the mouseup event happens.

BUGFIX. Prevent default of mousedown event that opens the dropdown

---

addon/components/basic-dropdown.js
tests/acceptance/open-and-immediatly-close-test.js
tests/dummy/app/controllers/open-and-immediatly-close.js
tests/dummy/app/router.js
tests/dummy/app/templates/open-and-immediatly-close.hbs

This prevents an exception to be raised when the dropdown is opened and
immediately closed, leading to event handlers in the root of the app 
that are never cleared.

Closing the dropdown cancels the pending times added when opening.

---

README.md
addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/opening-closing-order.hbs
tests/integration/components/basic-dropdown-test.js

- Add left, right or auto as new horizontal position options
- Add  top, bottom or auto as new vertical position options
You can force the component to be fixed in one position by passing `verticalPosition = top | bottom` and/or `horizontalPosition = right | left`.
- `{{#basic-dropdown}}` // verticalPosition="auto" and horizontalPosition="auto"
- `{{#basic-dropdown verticalPosition="top"}}` //  horizontalPosition="auto"
- `{{#basic-dropdown horizontalPosition="left"}}` //  verticalPosition="auto"
- `{{#basic-dropdown verticalPosition="top" horizontalPosition="left"}}`
related: https://github.com/cibernox/ember-basic-dropdown/issues/29

Add horizontalPosition and verticalPosition options

---

README.md
addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

`dropdownPosition` is aliased & deprecated to `verticalPosition` until 0.8
@tennisonchan I need to change the naming to be `above`/`below` to remain backwards compatible. I also aliased `dropdownPosition` to `verticalPosition` with a deprecation message to help people migrating to the new version.

`verticalPosition` can be auto/above/below

---

addon/components/basic-dropdown.js

Currently the dropdown width is stored in a variable and later on it's changed in the DOM, so the position calculation is performed with the old width. This PR fixes it by changing the width of the dropdown content before getting it with `getBoundingClientRect`.

Fix wrong positioning of content when matchTriggerWidth is true

---

addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

See cibernox/ember-power-select#254

Added labelledby, describedby and required aria properties to the trigger

---

addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

See https://github.com/cibernox/ember-power-select/issues/293#issuecomment-181419090

Implement all role & aria properties in RFC

---

addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
test-support/helpers/ember-basic-dropdown.js
tests/acceptance/opening-closing-order-test.js
tests/dummy/app/controllers/opening-closing-order.js
tests/dummy/app/templates/index.hbs
tests/integration/components/basic-dropdown-test.js

Just relying in synthetic mouse events to be fired by the browser when touch events are not handled is less than optimal, and caused problems with fastclick.
Now the dropdown is opened on `touchend` (unless the user scrolled since the `touchstart`). Effectively, it is opened/closed on `tap`.

Add event handlers for touch events.

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

This would allow the dropdown to be opened when the trigger is hovered over

Allow mouseenter and mouseleave events to be handled on the trigger

---

addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

Having this field being a special case was the source of some bugs
that had to do with the way the bindings were propagated. Bad shit.
All the component followed a strict DDAU policy except this field,
so I've removed it. You can still pass `initiallyOpened=true` to
render a component already opened, but it won't be updated anymore.
Any reaction to when a component is opened/closed has to be done
with the `onOpen`/`onClose` actions.

Remove double binding functionality in the `opened` property.

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
tests/dummy/app/templates/index.hbs
tests/integration/components/basic-dropdown-test.js

When any element inside the dropdown gets the focus, the entire dropdown gets a
`ember-basic-dropdown--focus-inside` class. That includes elements gaining the
focus inside the trigger or inside the dropdown, even if the dropdown is attached
somewhere else in the DOM tree.
When some element inside looses the focus, that class is removed.
This class is only added when the element gaining the focus is **inside** the dropdown,
not when the element is the dropdown itself has the focus.
Note: The trigger is considered to be a sub-component of the dropdown, and therefore
when the trigger is focused the class is added.
This feature is implemented using the `focusin`/`focusout` events. When the dropdown
is rendered in the root of the body, the component adds those events to the component
itself …

[FEATURE] Add `ember-basic-dropdown--focus-inside` class when something inside is focused

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

This gives the change to the user to prevent the action either by returning false or
by calling `e.preventDefault` on the received event.
The breaking behaviour is that when the action is called, `dropdown.isOpen` has still the old value, as expected.
I don't nobody was relying on this.

[BREAKING] onOpen and onClose now are called **before** opening/closing the component

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

After some experimentation, calling `e.preventDefault` was not a good idea. Calling it
on some events (keydown) by example will prevent other behaviour non related with this
component to work. And `return false` was already available.
Therefore, now return false is the new way to go to prevent the default behaviour
from happening.
The convention is:
- e.preventDefault will affect regular browser behaviour.
- return false will affect this component's behaviour only.

[BREAKING] Calling e.preventDefault on the event no changes the component's behavior

---

addon/components/basic-dropdown.js

Update to fix deprecation warning: http://emberjs.com/deprecations/v2.x/#toc_ember-component-didinitattrs

Move initialization logic from didInitAttrs to init hook

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

Unless the component receives `animationEnabled=true`.
Likewise, animations can be disabled by passing `animationEnabled=false` in
environments other than test.

Don't animate in test environment

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

Apparently is expected behaviour for all buttons to be triggered with space and enter.

Open close with the space bar.

---

addon/components/basic-dropdown/content.js

Currently the component is not working in IE9 due to two problems:
- IE9 does not implement 'classList', therefore adding and removing css-classes is not working. One solution is to use jQuery, another solution could be using a shim, see e.g. https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
- The 'getComputedStyle'-method does not consider 'transitionDuration' in IE9. Therefore 'transitionDuration' is undefined and a transition is always assumed.

Fix IE9 compatibility

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
index.js
testem.js
tests/integration/components/basic-dropdown-test.js

Problem to fix.
The `reposition` action sets some properties in the object, that are then propagated to other components. The problem is the reposition is invoked on a `didInsertElement` (because it needs to happen when the component is first opened) and also might be called at by a mutation observer callback and at user discretion.
All ideas I had either trigger a deprecation warning or break in testing mode.

Debug runloop problems

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
addon/templates/components/basic-dropdown/content.hbs
index.js
package.json

The main change is that animations don't directly interact with the DOM anymore (since successive re-renders will likely wipe any class added/removed outside the ember's world)
Updates Ember-cli

Fix varius issues

---

CHANGELOG.md
addon/components/basic-dropdown/content.js

In that case the component will fallback to the default. It makes the component
easier to compose

[BUGFIX] Allow to pass `to=destination` when destination is undefined

---

.npmignore

Its not alot of space but this reduces the install size by 2.7MB

Add fastboot-dist to npmignore

---

addon/components/basic-dropdown/content.js
bower.json

Trying the addon in glimmer made me realize the the current implementation was working just by chance, and that if Ember renders fast enough the styles would be calculated before the next frame and the animation wouldn't run.

Use requestAnimationFrame for animations

---

addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
tests/dummy/app/templates/index.hbs

This only affects the first reposition. The reason is that if the dropdown contains an input
with autofocus and it gets the focus before it has been property positioned, the page scrolls
to the top (or bottom, depending where the wormhole placeholder is) to put that input into
the viewport.
There is no way for any component inside the dropdown to wait to get the focus (do it in the
afterRender is not enough), therefore this hack.
The style property is still bound in ember, and successive repositions will go through the usual
ember binding system.

Make the first reposition apply styles directly instead of using ember.

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
tests/integration/components/basic-dropdown/content-test.js
tests/integration/components/basic-dropdown/trigger-test.js

This is breaking and would start the 0.14-beta.X series.

Rename `dropdown._id` to `dropdown.uniqueId` and make it public API

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/components/basic-dropdown/trigger.js
addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown/content-test.js
tests/integration/components/basic-dropdown/trigger-test.js

Initially I was over cautious because I wanted to prevent any memory leak in testing, but that actually means that if the app's root is not the body, the component doesn't close when clicking in that non-ember frame.

Stop caring about the app's root

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown/content-test.js

Reasons:
- It's a string, not a number. This is handy in case users what to construct DOM ids that start with
{{select.uniqueId), because DOM ids cannot start with numbers.
- It's already there, and might be handy to lookup the component in the container by that ID.

Make uniqueId to use Ember.guidFor

---

package.json

Closes #157
Since this issue (https://github.com/null-null-null/ember-get-config/issues/10), no calls special magic is required

Update ember-get-config to a version that works in fastboot

---

addon/components/basic-dropdown/content.js

The simple presence of a `transition` property is not enough to guarantee that
a transition is happening, because:
- It only fires if some change in the values affected by the transition, and there is no
easy way of knowing if a transition is running (unlike animations, which expose that information)
- There is some circunstance in which the animationEnd event doesn't fire depending on the browser,
by example if the element gets `display: none`.
Because of that, the only approach to animate the component with pure CSS is using CSS3 animations

The approach based in transitions is fundamentally flawed. Animations still work

---

addon/templates/components/basic-dropdown.hbs
tests/integration/components/basic-dropdown-test.js

There was a misalignment between the API yielded by actions and the one yielded to the block

Pass uniqueId in the public API yielded to the block.

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/utils/calculate-position.js

This makes easier to the end user to build their own repositioning strategy that
reuses some of the default logic. By example, if a user likes the default strategy
but wants some extra padding, it is now possible to pass a `calculatePosition` that
in turns call the default one, and the programmes just has to increase the `styles.top`
property in the desired amount.

The `calculatePosition` method is now inside /utils so users can import it

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/utils/calculate-position.js
tests/integration/components/basic-dropdown-test.js

Before this change, the object returned by `calculatePosition` looked
like:
```json
{"horizontalPosition":"right","verticalPosition":"below","style":{"top":"44.5px","right":"327.15625px"}}
```
After this change it looks like:
```
{"horizontalPosition":"right","verticalPosition":"below","style":{"top":44.5,"right":327.15625}}
```
This changes makes easier for people to rely on the default behaviour and manipulate
the values, since they are numbers instead of strings

Make the `calculatePosition` return numbers without units

---

addon/components/basic-dropdown/trigger.js

Chrome doesn't like it and it also prevents the inputs inside to get focus
and open the virtual keyboard in mobile

Don't call `e.preventDefault` on touchend

---

addon/components/basic-dropdown.js
tests/integration/components/basic-dropdown-test.js

We'd like to use eps `calculatePosition` hook in ember-paper. What is stopping us from that is that we need access to the component to get some options the user can provide.
We've done that through the function's context.
You probably don't want to leak internal stuff into public APIs, but this could be a solution for our problem.

call calculatePosition with context set to the component

---

.gitignore
addon/components/basic-dropdown/trigger.js
tests/integration/components/basic-dropdown/trigger-test.js

When using the Ember Basic Dropdown with custom events, it is sometimes desirable (in my case necessary) to override the default event handlers, particularly when working with the `mouseenter`/`mouseleave` optional handlers. 
Also added `dropdown` as a parameter for the default handlers (and their bound overrides, if applicable) for consistency with the optional handlers. 
Added tests for the new functionality, and aimed for consistency with existing test suite and application code. 
Thanks for the great project!

Permit overrides of default handleMousedown, handleKeydown, handleTouchend actions

---

CHANGELOG.md
addon/components/basic-dropdown/trigger.js
tests/dummy/app/styles/components/main-header.scss
tests/dummy/app/styles/demos/content-mouse-enter-leave.scss
tests/integration/components/basic-dropdown/trigger-test.js

Remove `aria-pressed` logic. It’s still bound, but doesn’t show by default

---

CHANGELOG.md
test-support/helpers/ember-basic-dropdown.js
tests/acceptance/helpers-test.js
tests/dummy/app/templates/helpers-testing.hbs

This will be backported to 0.22.X

[BUGFIX] Fix `clickDropdown` test helper to work when the given selector already belongs the trigger

---

CHANGELOG.md
addon/templates/components/basic-dropdown/content.hbs

Part of #218 
/cc @steveszc can you verify that this makes a difference and the fact the the div moves from beneath the input to the root of the body is not a problem? Render the div in the wormhole has a couple issues. Because it some glimmer2 limitations having an IF right inside an ember-wormhole, without a stable parent, causes a render problem (well know issue).

Have a constant element in DOM

---

addon/components/basic-dropdown/trigger.js
test-support/helpers/ember-basic-dropdown.js
tests/integration/components/basic-dropdown/trigger-test.js

If `e.target` is an SVG element `click()` method doesn't exist. jQuery takes care of that.

Fix touch handler synthetic click

---

package.json

I verified this causes ember-native-dom-helpers to be added to node_modules in my app.

[Fixes #231] Move ember-native-dom-helpers to dependencies

---

addon/utils/calculate-position.js

This fixes https://github.com/cibernox/ember-basic-dropdown/issues/262, by using `document.body.clientWidth` instead of `window.innerWidth` to calculate the screen width.

Fix calculation of position to take scroll bars into account

---

README.md
ember-cli-build.js
tests/dummy/app/templates/public-pages/docs/test-helpers.hbs
tests/dummy/app/templates/snippets/test-helpers-4-js.js
tests/dummy/app/templates/snippets/test-helpers-5-js.js
tests/dummy/app/templates/snippets/test-helpers-6-js.js

Some small documentation updates. 
Included babel polyfill because tests were giving `regeneratorRuntime is not defined ember` errors.

Documentation update

---

CHANGELOG.md
addon/components/basic-dropdown.js
addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
tests/dummy/app/templates/public-pages/docs/api-reference.hbs
tests/integration/components/basic-dropdown-test.js
tests/integration/components/basic-dropdown/content-test.js

Passing `to="id-of-elmnt"` to the `{{#dropdown.content}}` component is deprecated.
The way to specify a different destination for `ember-wormhole` is now by passing
`destination=id-of-elmnt` to the top-level `{{#basic-dropdown}}` component.
The old property `to=` still works but shows a deprecation message and will
be removed soon.

[BREAKING] Introduce `destination=`. Deprecate `to`.

---

CHANGELOG.md
addon/components/basic-dropdown/content.js
tests/dummy/app/styles/_base.scss

If the wormhole destination is a direct child of the BODY element, there
is no need to reposition it after every scroll event, since the origin
of coordinates is the scrollable element itself.
This is the case for almost every dropdown. That method, albeit fast, can be called tens of times per second, so I expect this to matter quite a lot.

[PERF] Optimize number of reposition calls

---

addon/components/basic-dropdown/content.js

This is the simple fix I mentioned in https://github.com/cibernox/ember-power-select/issues/788. It should work for the case I presented in [this comment](https://github.com/cibernox/ember-power-select/issues/788#issuecomment-301711808).
Unfortunately, I was unable to make a test case for this, as it seems almost impossible to replicate the sort of user interaction required to trigger the bug.

Handle undefined positioning when the dropdown is opened and closed at the same time

---

addon/components/basic-dropdown/trigger.js

Investigated because I was receiving tons of `Not enough arguments to MouseEvent.initMouseEvent` in production from mobile Android Firefox browsers and stumbled on this: 
https://stackoverflow.com/questions/26761625/not-enough-arguments-to-mouseevent-initmouseevent?answertab=active#tab-top

Fix mobile Firefox issue with invoking the click event

---

addon/components/basic-dropdown/content.js

this fixed:
when dropdown is open and clicking on the scrollbar on page, a JS error is generated:

fixed a bug when el is document and doesn't have classList

---

.gitignore
.travis.yml
addon/components/basic-dropdown/content.js
ember-cli-build.js
package.json
testem.js
tests/dummy/app/app.js
tests/dummy/app/index.html
tests/dummy/config/environment.js
yarn.lock

[The RFC to drop IE9 and 10 from the support matrix for Ember 3.0](https://github.com/emberjs/rfcs/pull/252) made me consider doing the same thing here.
This addon didn't support IE9 already, but it kind of supported IE10 despite of the lack of `MutationObserver`.
This drops support for it officially, and I'm thinking about publishing 1.0 after this.

Remove support IE10

---

CHANGELOG.md
README.md

I got a little lost down a rabbithole due to IE10 compatibility being dropped in a patch release, hopefully this helps others.
It might also be worth adding a note to lock to 0.33.5 for IE10 compat in the README?

Add removal of IE10 support to Changelog

---

addon/components/basic-dropdown/content.js
addon/templates/components/basic-dropdown.hbs
addon/utils/scroll-helpers.js
app/utils/scroll-helpers.js
tests/dummy/app/templates/public-pages/docs/api-reference.hbs
tests/integration/components/basic-dropdown/content-test.js
tests/unit/utils/scroll-helpers-test.js

Platform-supplied `select` boxes do not allow scrolling once a `select` is open. This approximates that behavior. (Doesn't work beyond a frame boundary, but works completely within the present `window` context.)

Prevent scrolling as an option.

---

app/styles/ember-basic-dropdown.less

There was a fix for a css bug in efc059a047085065624ec281dbbb9891b885e325 that never ended up in the `.less` file.  This adds it.

Add css fix from previous commit into less file

---

addon/utils/calculate-position.js

If `destination.parentNode` is not an Element, `window.getComputedStyle` would raise an assertion.

Remove unneeded condition.

---

addon/components/basic-dropdown/content.js
addon/utils/scroll-helpers.js
tests/unit/utils/scroll-helpers-test.js

This improves the code that code in several ways.
* [Fix deltaX and deltaY calculation](https://github.com/cibernox/ember-basic-dropdown/commit/090d252bc3afffdf00291a44c4fd645898914e45) fixes a bug in part of the code (and later another one is fixed while refactoring).
* [Extract standardizing deltas to scroll helpers](https://github.com/cibernox/ember-basic-dropdown/commit/80322ee13b07fa9222b289f642f08e9adae9cdc7): there are several delta modes (some browsers might measure this in lines or even in pages), the code that standardises these deltas to be measured in pixel is extracted to scroll helpers and refactored, extracting and documenting some constants along the way.
* [Deinterlace reads and writes when scrolling](https://github.com/cibernox/ember-basic-dropdown/commit/3edda0a274bf4850 …

Better scrolling

---

addon/components/basic-dropdown.js

When an app has a newer version of @ember/test-helpers without using
the new testing API, using EBD and EPS breaks.

Fix testing bug

---

tests/dummy/app/templates/snippets/dropdown-events-3-js.js
tests/dummy/app/templates/snippets/dropdown-events-4-js.js

The controller code snippets for the `onClose` and `onFocus` events are blank. This PR adds the missing snippets, so that the controller code is displayed.

Add dropdown-events-3-js and dropdown-events-4-js code snippet

---

tests/dummy/app/templates/snippets/custom-position-1-js.js

I got a lint error after copy-pasting this snippet in my code editor

Remove extra space in documentation snippet

---

README.md

Without this prefix, the link get's built to `<a href="/cibernox/ember-basic-dropdown/blob/master/www.ember-twiddle.com">Ember Twiddle</a>` instead of actually linking to twiddle.

Adds "https" to ember-twiddle link in readme

---

addon/components/basic-dropdown-content.js
addon/components/basic-dropdown-trigger.js
addon/templates/components/basic-dropdown-trigger.hbs
tests/dummy/app/templates/public-pages/docs/api-reference.hbs
tests/integration/components/basic-dropdown-test.js
tests/integration/components/content-test.js
tests/integration/components/trigger-test.js

There's a bit more boiler plate for users, but greatly simplifies that users have to know.

Now that element modifiers can be forwarded we don't need to attach events ourselves

---

CHANGELOG.md
addon/components/basic-dropdown-content.js

It turns out the top/left/right/width/height properties passed to the dropdown weren't
being used at all

BUGFIX Content didn't reposition after scroll or resize events

---

addon/utils/calculate-position.ts

If using auto vertical positioning, and there is not enough space either above or below, the dropdown should always be positioned below - this way, the page will at least expand to show the dropdown, whereas it will be cut off if it moves out of the screen above.
Fixes #505

Fall back to verticalPosition="below" if there isn't enough space either way

---

addon/components/basic-dropdown-content.js

Ember uses comment nodes to keep track of the component boundaries.
I was detecting some unneeded repositions because the mutation observers were detecting these comment nodes insertions/deletions.
I also went ahead and filtered out empty text nodes as well.
`Array.prototype.slice.call` was used to convert a `NodeList` to an array because it is faster than `Array.from()`. Source: https://stackoverflow.com/a/49822981

ignore comment node changes on mutation observer

---

addon/components/basic-dropdown.js

The problem here was that the `otherStyles` property was being mutated here https://github.com/cibernox/ember-basic-dropdown/blob/v3/addon/components/basic-dropdown.js#L182
On the next reposition, those styles would be there and could result in unexpected behavior.

fix otherStyles changes

---

addon/components/basic-dropdown.js

This is very important because some position calculations might rely on the existing dimensions.
If we don't reset otherStyles, the dropdown is rendered with the previously applied styles, which might affect the position calculation.

reset `otherStyles` on closing

---

addon/components/basic-dropdown-content.js

If `@animationEnabled={{false}}` is passed, the getter will not use it

Fix animationEnabled getter to account for false value

---

index.js

Fixes #544
After updating `ember-power-select` to `4.0.0` our app was erroring with:
> Could not find module `ember-compatibility-helpers` imported from `@glimmer/component/index`
Replicated the changed made in cibernox/ember-power-select/pull/1244
With these changes our app no longer breaks.

Always call _super.included

---

addon/components/basic-dropdown-content.js
addon/components/basic-dropdown.js
addon/templates/components/basic-dropdown.hbs
addon/utils/calculate-position.js
tests/dummy/app/templates/public-pages/docs/api-reference.hbs
tests/dummy/app/templates/public-pages/docs/custom-position.hbs
tests/integration/components/basic-dropdown-test.js
tests/integration/components/content-test.js

This adds support for handling `style.bottom` if it’s returned from `calculatePosition()`.
`top`, `left` and `right` are already supported, so now with `bottom` we have the complete set! 🙂

Support custom positioning using `bottom` property

---

addon/templates/components/basic-dropdown-trigger.hbs
tests/integration/components/trigger-test.js

aria-expanded is a property that must always be set when used, to either `"true"` when expanded, or `"false"` if collapsed. Omitting it when collapsed means that assistive technologies aren't aware that this element is expandable.
Closes #555 .

Issue 555 - Always set aria-expanded, also when collapsed.

---

addon/components/basic-dropdown-content.ts

This issue was addressed partially in the previous commit: 702f15052bbb124de2a2c9ede6a2dc436e470ffe, however, there's another type definition also have the same problem: https://github.com/cibernox/ember-basic-dropdown/blob/809ac756022a5e2e249bc8cba3ef080b58f440cf/addon/components/basic-dropdown-content.ts#L34 and been used on here: https://github.com/cibernox/ember-basic-dropdown/blob/809ac756022a5e2e249bc8cba3ef080b58f440cf/addon/components/basic-dropdown-content.ts#L126 and here: https://github.com/cibernox/ember-basic-dropdown/blob/809ac756022a5e2e249bc8cba3ef080b58f440cf/addon/components/basic-dropdown-content.ts#L130
This PR is going to fix the remaining type errors and has been tested successfully.
@cibernox I'm sorry that I should've mention there're multiple occurrences of this …

fix event type on RootMouseDownHandler

---

README.md

The minimum emberjs version for version 2 should be 3.13 as version 2 uses glimmer components and that is only available for emberjs version 3.13 or greater(around the time you were finally able to enable octane before it became the default in 3.16).
For version 1.x, the `ember-try.js` uses emberjs 2.16.0 as it's minimum from what I saw.

Updated ember compatibility in the readme to match up with the minimum version that is in the ember-try.js file for version 2 and 1.

---

addon/utils/calculate-position.ts

`horizontalPosition="center"` was being ignored if you were using both `verticalPosition="above"` and `renderInPlace="true"`.
`positionData.style` was being overwritten in the `verticalPosition === 'above'` block - only the `top` prop should be modified

Fix horizontalPosition="center" when using verticalPosition="above" & renderInPlace="true"

---

package.json

This avoids users having to use `resolutions` to update to ember-truth-helpers v3 :)

Widen `ember-truth-helpers` dependency constraint to allow v3.x

---

addon/components/basic-dropdown-content.ts
addon/templates/components/basic-dropdown-content.hbs
package-lock.json
package.json
tests/integration/components/basic-dropdown-test.js

Currently the positioning of the basic dropdown content requires you to use an `unsafe-inline` directive if you're using a [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). This PR changes the positioning of the content from an inline, html-safe string to using https://github.com/jelhan/ember-style-modifier which adds the styles in a CSP-friendly way.
I'm not sure if you're interested in this change as it brings in a few deps, and I'm not sure what your compatibility story is. I think it's worth it and I believe the change is non-breaking.
Thanks!

CSP-safe positioning

---

package.json
testem.js
yarn.lock

~Congrats! EBD has no memory leaks (at least no memory leaks caused by codepaths exercised by the test suite).~
Oops I just noticed that CI does not appear to be running, but the test suite did not fail locally with this new addon installed
This PR installs an add-on I authored called ember-cli-memory-leak-detector.
The add-on works by recording a heap snapshot after the suite tests finishes running. The heap snapshot is then searched for any retained instances of the host app/addon's ES classes (indicating a memory leak). If it finds retained classes in the heap snapshot, the test suite fails and a report of the retained classes is logged in the console output.
After installing ember-cli-memory-leak-detector we can confirm that EBD has no memory leaks, and we can ensure that no memory …

Install ember-cli-memory-leak-detector

---

addon/components/basic-dropdown.ts
addon/templates/components/basic-dropdown-content.hbs
tests/integration/components/basic-dropdown-test.js

In  #591 I aimed to make this work with a strict CSP, and it did for the most part. We got around to using it (via ember-power-select) and were still seeing a few errors.
This adds the same `{{style}}` modifier usage to the `<Element>` rendered if `@htmlTag` is passed.
The initial opening now uses `element.style.setProperty` instead of `element.setAttribute` which is not CSP-safe.

use style modifier in the content else block too

---

.gitignore
addon/components/basic-dropdown-content.ts
addon/components/basic-dropdown.ts
package-lock.json
package.json
tests/integration/components/content-test.js

The current way to conditionally import `@ember/test-helpers/dom/get-root-element` breaks in an app using embroider with:
```
staticAddonTestSupportTrees: true
```
This PR refactors this to instead use `@embroider/macros`, which can be statically analyzed. Functionally, nothing should change, I think. I tried it in an app and it worked fine.

Use `@embroider/macros` to conditionally import `@ember/test-helpers`

---

addon/components/basic-dropdown-content.ts
addon/components/basic-dropdown.ts
addon/templates/components/basic-dropdown-trigger.hbs
tests/integration/components/basic-dropdown-test.js
tests/integration/components/trigger-test.js

Closes https://github.com/cibernox/ember-basic-dropdown/issues/557.
This mostly just fixes the merge conflicts present in https://github.com/cibernox/ember-basic-dropdown/pull/558.
To re-iterate, this commit uses `aria-controls` instead of `aria-owns` to build the relationship between the trigger and its content. In addition, the `aria-owns` property is migrated to the trigger's parent.
This fixes an issue I ran into using Apple's VoiceOver software, in which I couldn't use the movement commands (VO+right-arrow) to navigate into dropdown menus created with ember-basic-dropdown.

Fixes usage of aria-owns/controls in trigger

---

addon/components/basic-dropdown.ts

Use `Object.assign` instead of `Ember.assign`, as that is deprecated here: https://github.com/emberjs/rfcs/blob/master/text/0750-deprecate-ember-assign.md
This basically means that support for IE11 is dropped. I guess you could still run this with IE11 by providing a global polyfill yourself for `Object.assign`.

Avoid deprecation for `import { assign } from '@ember/polyfills'`

---

CHANGELOG.md
addon/components/basic-dropdown-content.ts
tests/integration/components/basic-dropdown-test.js

This is already opened pr on this Issue cibernox#623
but i am not sure we should make any changes on this code [ember-basic-dropdown](https://github.com/cibernox/ember-basic-dropdown/pull/623/files#diff-5eb8bde405ea618cba05ea05b9898dc60ff96ac459a953c279fbb24f39a46f81L128-L132), cause on production code - it works good, the only problem with tests, so i made a workaround for testing purpose. Any idea how to fix this issue better, very welcome.
The transitioning--in etc classes don't get reset after the first render. When the dropdown content first renders, it animates correctly, but on subsequent renders there is no animation - cause state not being reset to correct value.
Looks like it was broken here in this commit, so idea to revert back and cover with tests: …

Fixed state not being reset to correct value when transitioning out

---

addon/components/basic-dropdown-content.ts

This is a follow-up to the PRs #623 and #628. The fix on the animation flow worked well when the dropdown is rendered in place. Not so well when not because the parent element is lost when the content element is closed.
In the `animateOut` function, there's an early exit when no `dropdownElement.parentElement` is null. So before the check I just try to get the parentElement through the `destinationElement`.

Make sure the content parent element is set before animating out

---

tests/dummy/app/controllers/public-pages/docs.js
tests/dummy/app/styles/_utilities.scss
tests/dummy/app/styles/components/main-header.scss
tests/dummy/app/templates/public-pages/docs.hbs

This PR fixes the docs styles on mobile layout. 
1. The width of the content wrapper divs was fixed to 1024px with a max-width of 1024px. So I switched the width to be 100%. 
https://user-images.githubusercontent.com/176766/152803909-444293cc-5bb3-4e93-83a5-3e93ef5241f6.mov
2. I also added an `overflow-x` to the header links on mobile in case it overflows
3. In the `docs` page, I made the `groupedSections` the source of truth for both navigations (main nav and the native select on mobile)
4. It was missing the animations page on mobile

Fix docs mobile layout

---

README.md

This PR updates the CI badge Status that was pointing to the latest failed CI build on Travis. It is now pointing to the latest CI GitHub Actions workflow status.

Update CI Status Badge to GitHub Actions

---

addon/components/basic-dropdown.ts

The 'ember-basic-dropdown' config key is technically defined correctly as:
```
'ember-basic-dropdown': {
destination: string
} | undefined
```
Which means that it might be `undefined` and the client app might not have it set. So far so good.
The problem with the type occurs when the client app does not have it defined in  its own `config/environment.d.ts` .
During build the config type is set to the clients app type that  when `ember-basic-dropdown` field type is not set, we get this type error:
```
Property 'ember-basic-dropdown' does not exist on type '{ environment: string; modulePrefix: string; podModulePrefix: string; locationType: string; rootURL: string;}; ...}
```
**The fix:** 
- Added type assertion to config in destination element.
When accessing `ember-basic-dropdown` field on …

Type error fix:  `ember-basic-dropdown` does not exist on type  {environment: string; ...}

---

addon/modifiers/basic-dropdown-trigger.ts

Follow up to https://github.com/cibernox/ember-basic-dropdown/pull/626
Fixes some deprecations - was still using the deprecated ember-modifier API in places. Specifically in regards to using `this.args` and `this.isDestroyed`

refactor: fix deprecations from trigger modifier

---

package.json

This allow ember-get-config dependency to be v2.0.0
This addon was forcing the v1 on my app which caused trouble building, started happening yesterday don't know why, with v2 everything works.

Allow ember-get-config v2

---

package-lock.json
package.json

Versions below v2.1 should be avoided, see:
- https://github.com/mansona/ember-get-config/releases/tag/v2.1.0
- https://github.com/mansona/ember-get-config/pull/45

Update `ember-get-config` to v2.1

---

addon/components/basic-dropdown-content.ts

Fixes https://github.com/cibernox/ember-basic-dropdown/issues/550
This argument is documented in both ember-basic-dropdown and ember-power-select, but never actually used or passed along. I'll also create a PR in ember-power-select to pass the argument along.

Allow passing @animationEnabled argument to BasicDropdownContent

---

.github/workflows/ci.yml
config/ember-try.js
ember-cli-build.js
package-lock.json
package.json
tests/dummy/app/components/snippets/trigger-events-3.js
tests/dummy/config/deprecation-workflow.js
tests/dummy/config/environment.js

fix #704 
Changes:
* [Internal] update `ember-concurrency` to `v3.0` (needs internal node v14 drop) (see https://github.com/machty/ember-concurrency/blob/3.0.0/CHANGELOG.md#300)
* [Internal] minor package updates
* [Internal] fix deprecations
* [Internal] remove unused packages (`ember-disable-prototype-extensions`, `ember-export-application-global`, `ember-maybe-import-regenerator`)
* [Internal] cleanup unused code in `ember-cli-build.js`
There is no braking change, for consumer app. If we want, we can drop nodejs 14 generally, because the LTS has ended on 30 april 2023
Tests for ember-release, canary... are failing because `ember-render-modifiers` needs a release with peerDependency for ember v5. They have already added in there package.json, but there is atm not released.

Update ember to v4.12 & some cleanups

---

index.js

Based on suggestion by @fastindian84, this fixes the following error with Ember 5.0.0:
```
Cannot read properties of undefined (reading 'ember-cli-sass')
```
Fixes #706

Fixed support for Ember 5.0.0

---

.github/workflows/ci.yml
config/ember-try.js
package-lock.json
package.json

There was released a new version of [ember-element-helper](https://github.com/tildeio/ember-element-helper/blob/v0.7.1/ember-element-helper/CHANGELOG.md). No braking changes, only added support for `ember-source` v5.

Update ember-element-helper to v0.7.1

---

addon/components/basic-dropdown-content.hbs
addon/components/basic-dropdown-content.ts
package-lock.json
package.json
tests/dummy/app/components/autofocus-input.js
tests/dummy/app/templates/components/autofocus-input.hbs

Replaces the no-longer-recommended [render lifecycle modifiers](https://github.com/emberjs/ember-render-modifiers) with local function modifiers.
`@ember/render-modifiers` were meant as a transitional tool from the pre-Octane era, and not long-term usage.
Modifier code is directly ported from the setup/teardown hooks with no changes except what I've pointed out in code comments.
Recommend reviewing commit-by-commit.

Drop `@ember/render-modifiers`

---

package-lock.json
package.json
testem.js

Remove `ember-cli-memory-leak-detector` while there is not compatible with latest qunit (see https://github.com/steveszc/ember-cli-memory-leak-detector/issues/49)
This bug brings timeout in test

Remove `ember-cli-memory-leak-detector`

---

tests/dummy/config/ember-try.js

While updateing ember-cli i have seen that we have added workaround for embroider-tests some months ago.
This should not anymore necessary as we have updated in the last time a lot of packages

Remove `ember-cli-htmlbars` workaround in ember-try

---

package-lock.json
package.json

While ember-cli update to 4.12.2 (https://github.com/cibernox/ember-basic-dropdown/pull/716) there were added wrong `peerDependencies`

Fix peerDependency of ember-source in package.json

---

package-lock.json
package.json

As we have already braking changes (specially after we move this addon to v2), we should also drop old dependency versions.
This gives us the guarantee that consumer apps use also the latest versions of dependencies.

Allow only latest version in dependencies

---

docs/app/templates/public-pages/docs/styles.hbs

docs: Fix that code snippets were rendered as [object Object]

---

ember-basic-dropdown/_index.scss
ember-basic-dropdown/ember-basic-dropdown.scss
ember-basic-dropdown/package.json

Add option for consumer apps to use import `@import 'ember-basic-dropdown.scss'`
this works with `ember-cli-scss` only by adding `scssOptions`
```js
let app = new EmberApp(defaults, {
...
sassOptions: {
includePaths: ['node_modules/ember-basic-dropdown'],
},
...
});
```

Add option to use `ember-basic-dropdown.scss`

---

ember-basic-dropdown/package.json
ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
ember-basic-dropdown/src/components/basic-dropdown.ts
pnpm-lock.yaml

`ember-get-config` was added some years ago to fix TS error, but there were no benefit...
For this reason we can drop it, and use directly with ts line error disable rule like other addons

Remove ember-get-config

---

docs/app/templates/public-pages/docs/api-reference.hbs

Add `destinationElement` in docs which was added in #791 for shadow dom support

DOCS: Add `destinationElement` to api-reference

---

ember-basic-dropdown/rollup.config.mjs

Starting with beta v8.0.0.beta.6 there was missing the `styles.js` export

Fix rollup config (style.js -> styles.js)

---

docs/app/templates/public-pages/docs/api-reference.hbs

I noticed this argument wasn't documented.
This is related to https://github.com/cibernox/ember-power-select/pull/1819, where we now set this property.

Document @rootEventType

---

ember-basic-dropdown/src/components/basic-dropdown-content.ts
ember-basic-dropdown/src/components/basic-dropdown.ts

In PR #903 we have discovered that the type of `rootEventType` was not aligned.
In additional to complete https://github.com/cibernox/ember-power-select/pull/1819 we need to export possible types

Improve `rootEventType` type and export for EPS

---

ember-basic-dropdown/src/utils/calculate-position.ts

We noticed that in certain use cases the dropdown is not correctly positioned horizontally when the body is set to `position: relative` and you scroll horizontally. When digging through some issues and the code I discovered this [fix](https://github.com/cibernox/ember-basic-dropdown/pull/333) for vertical positioning. I believe that we should also implement a similar fix for horizontal positioning. We've patched this dependency in our own app and have verified that it works.
Reproducible use case (scroll to the right, then open a dropdown): https://stackblitz.com/edit/ember-cli-editor-output-1hdarw?file=app%2Ftemplates%2Fapplication.hbs,app%2Fstyles%2Fapp.css,app%2Fapp.js&title=Ember%20Starter

Fix dropdown not correctly positioned horizontally when body position is relative

---

.github/workflows/push-dist.yml

Discoverd that there is atm missing the dist push, which was added in addon-blueprint

Add push dist workflow

---

ember-basic-dropdown/src/utils/calculate-position.ts

In some parts of our app, when we override the calculatePosition we have necessary to use types of `CalculatePositionOptions`. We should export it

Export interface `CalculatePositionOptions`

---

ember-basic-dropdown/package.json
ember-basic-dropdown/rollup.config.mjs
pnpm-lock.yaml

`rollup-plugin-styles` is not anymore maintained so we need to switch to an other rollup tool
`rollup-plugin-sass` is a good alternative for `rollup-plugin-styles`

Replace scss to css compiler while rollup

---

ember-basic-dropdown/src/components/basic-dropdown.ts

This adds two missing exports for `BasicDropdown`. These exports help, e.g., to correctly reference and type the Dropdown's blocks in components re-yielding the `BasicDropdown` blocks.

Export interfaces `BasicDropdownSignature`, `BasicDropdownArgs` and `BasicDropdownDefaultBlock`

---

ember-basic-dropdown/eslint.config.mjs
ember-basic-dropdown/src/components/basic-dropdown-content.ts
ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts
ember-basic-dropdown/src/components/basic-dropdown.ts
ember-basic-dropdown/src/modifiers/basic-dropdown-trigger.ts
ember-basic-dropdown/src/utils/calculate-position.ts

When we were moved from 5.12 to 6.1 we have disabled some eslint rules.
Now we fix this issues and do also improve typing. We remove latest `any` and `Function`
To fix unbound function there was necessary to make a workaround inside addon, so we don't need to publish this as braking

Reactivate eslint rules & improve typings

---

ember-basic-dropdown/package.json

- @glimmer/tracking is provided by ember-source
- ember-source is assumed by both embroider and ember-cli in ways that it doesn't actually need to be a peer, and having it as one creates potential for duplicate copies that create errors in apps

Remove ember-source and glimmer tracking as a peer dependency

---

ember-basic-dropdown/src/components/basic-dropdown-content.ts
test-app/tests/integration/components/basic-dropdown-test.js

The event on shadowRoot element was never removed correctly...
this is the fix for reported bug #965...
> repro
> 
>     * click on trigger -> it opens
> 
>     * click on something inside dropdown -> it stays open
> 
>     * click on trigger 2d time-> it opens
> 
>     * click on something inside dropdown -> it does NOT stay open

Fix removing event listener for shadow root element

---

docs/app/templates/public-pages.hbs

Seen in docs, that we have a link to v1 docs, which is broken. V1 is very old so we don't need to fix it

Remove broken v1 docs link
